repos:
  # Ruff - Linting
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.13.1
    hooks:
      - id: ruff
        name: ruff-lint
        args: [ --fix ]

  # Ruff - Formatting
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.13.1
    hooks:
      - id: ruff-format
        name: ruff-format

  # Mypy - Type checking
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.18.2
    hooks:
      - id: mypy
        args: [ "--config-file=pyproject.toml" ]
        additional_dependencies:
          - pydantic
          - types-requests