repos:

  # Ruff
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.13.2
    hooks:
      - id: ruff-check
        args: [ --fix ]
      - id: ruff-format

  # Mypy
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.18.2
    hooks:
      - id: mypy
        args: [ --config-file=pyproject.toml ]
        additional_dependencies:
          - pydantic
          - types-requests
