name: Build & Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  python-wheel-upload:
    name: Build & Upload Python Wheel
    runs-on: ubuntu-latest
    outputs:
      wheel_file: ${{ steps.build_wheel.outputs.wheel_file }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install uv
        run: pip install uv

      - name: Build Python Wheel
        id: build_wheel
        run: |
          uv build --wheel
          wheel_file=$(basename dist/*.whl)
          echo "wheel_file=$wheel_file" >> $GITHUB_OUTPUT

      - name: Upload Wheel Artifact
        uses: actions/upload-artifact@v4
        with:
          name: python-wheel
          path: dist/${{ steps.build_wheel.outputs.wheel_file }}

  docker-build-push:
    name: Build & Push Docker Image
    needs: python-wheel-upload
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      AIRFLOW_VERSION: "3.0.6"
      PYTHON_VERSION: "3.12"
      IMAGE_NAME: docker.io/${{ secrets.DOCKERHUB_USERNAME }}/airflow
      WHEEL_NAME: ${{ needs.build-and-upload-wheel.outputs.wheel_file }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Download Wheel Artifact
        uses: actions/download-artifact@v4
        with:
          name: python-wheel
          path: dist/

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Extract Docker Metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE_NAME }}

      - name: Build & Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            AIRFLOW_VERSION=${{ env.AIRFLOW_VERSION }}
            PYTHON_VERSION=${{ env.PYTHON_VERSION }}
            WHEEL_FILE=${{ env.WHEEL_NAME }}