name: Wheel Build & Upload

on:
  push:
    branches:
      - main

jobs:
  build-and-upload-wheel:
    name: Wheel Build & Upload
    runs-on: ubuntu-latest
    outputs:
      wheel_file: ${{ steps.build_wheel.outputs.wheel_file }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install uv
        run: pip install uv

      - name: Build Python Wheel
        id: build_wheel
        run: |
          uv build --wheel
          wheel_file=$(basename dist/*.whl)
          echo "wheel_file=$wheel_file" >> $GITHUB_OUTPUT

      - name: Upload Wheel Artifact
        uses: actions/upload-artifact@v4
        with:
          name: python-wheel
          path: dist/${{ steps.build_wheel.outputs.wheel_file }}